# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1316, 650)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 80, 831, 521))
        self.groupBox.setObjectName("groupBox")
        self.Status = QtWidgets.QLabel(Form)
        self.Status.setGeometry(QtCore.QRect(40, 600, 151, 21))
        self.Status.setObjectName("Status")
        self.counter = QtWidgets.QLabel(Form)
        self.counter.setGeometry(QtCore.QRect(760, 600, 91, 16))
        self.counter.setObjectName("counter")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(920, 510, 151, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.ResultEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.ResultEdit.setGeometry(QtCore.QRect(10, 20, 131, 61))
        self.ResultEdit.setObjectName("ResultEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(930, 170, 287, 204))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.Set_T1_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_T1_max.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_T1_max.setObjectName("Set_T1_max")
        self.gridLayout.addWidget(self.Set_T1_max, 2, 1, 1, 1)
        self.Set_pp1_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_pp1_min.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_pp1_min.setObjectName("Set_pp1_min")
        self.gridLayout.addWidget(self.Set_pp1_min, 1, 2, 1, 1)
        self.Set_T2_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_T2_max.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_T2_max.setObjectName("Set_T2_max")
        self.gridLayout.addWidget(self.Set_T2_max, 4, 1, 1, 1)
        self.Set_pp2_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_pp2_max.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_pp2_max.setObjectName("Set_pp2_max")
        self.gridLayout.addWidget(self.Set_pp2_max, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.Set_pp1_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_pp1_max.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_pp1_max.setObjectName("Set_pp1_max")
        self.gridLayout.addWidget(self.Set_pp1_max, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.Set_T2_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_T2_min.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_T2_min.setObjectName("Set_T2_min")
        self.gridLayout.addWidget(self.Set_T2_min, 4, 2, 1, 1)
        self.Set_pp2_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_pp2_min.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_pp2_min.setObjectName("Set_pp2_min")
        self.gridLayout.addWidget(self.Set_pp2_min, 3, 2, 1, 1)
        self.Set_T1_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_T1_min.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_T1_min.setObjectName("Set_T1_min")
        self.gridLayout.addWidget(self.Set_T1_min, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.Set_pp3_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_pp3_max.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_pp3_max.setObjectName("Set_pp3_max")
        self.gridLayout.addWidget(self.Set_pp3_max, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.Set_pp3_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_pp3_min.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_pp3_min.setObjectName("Set_pp3_min")
        self.gridLayout.addWidget(self.Set_pp3_min, 5, 2, 1, 1)
        self.OpenAutoJudge = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.OpenAutoJudge.setEnabled(True)
        self.OpenAutoJudge.setObjectName("OpenAutoJudge")
        self.gridLayout.addWidget(self.OpenAutoJudge, 0, 0, 1, 1)
        self.Set_T3_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_T3_max.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_T3_max.setObjectName("Set_T3_max")
        self.gridLayout.addWidget(self.Set_T3_max, 6, 1, 1, 1)
        self.Set_T3_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Set_T3_min.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Set_T3_min.setObjectName("Set_T3_min")
        self.gridLayout.addWidget(self.Set_T3_min, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.pp_value_max = QtWidgets.QLabel(Form)
        self.pp_value_max.setGeometry(QtCore.QRect(930, 50, 371, 21))
        self.pp_value_max.setObjectName("pp_value_max")
        self.pp_value_min = QtWidgets.QLabel(Form)
        self.pp_value_min.setGeometry(QtCore.QRect(930, 80, 371, 20))
        self.pp_value_min.setObjectName("pp_value_min")
        self.period = QtWidgets.QLabel(Form)
        self.period.setGeometry(QtCore.QRect(930, 110, 371, 21))
        self.period.setObjectName("period")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(940, 380, 191, 16))
        self.label_9.setObjectName("label_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 401, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.SerOpenBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SerOpenBtn.setObjectName("SerOpenBtn")
        self.horizontalLayout.addWidget(self.SerOpenBtn)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(910, 420, 371, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 339, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.quantityEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.quantityEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.quantityEdit.setObjectName("quantityEdit")
        self.horizontalLayout_2.addWidget(self.quantityEdit)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.timesEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.timesEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.timesEdit.setObjectName("timesEdit")
        self.horizontalLayout_2.addWidget(self.timesEdit)
        self.CalibrationBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.CalibrationBtn.setObjectName("CalibrationBtn")
        self.horizontalLayout_2.addWidget(self.CalibrationBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "永磁转子磁场检测系统"))
        self.groupBox.setTitle(_translate("Form", "图像"))
        self.Status.setText(_translate("Form", "TextLabel"))
        self.counter.setText(_translate("Form", "已检测:0"))
        self.groupBox_3.setTitle(_translate("Form", "检测结果"))
        self.label.setText(_translate("Form", "峰-峰值1"))
        self.label_5.setText(_translate("Form", "峰-峰值3"))
        self.label_2.setText(_translate("Form", "周期1"))
        self.label_7.setText(_translate("Form", "最大值"))
        self.label_8.setText(_translate("Form", "最小值"))
        self.OpenAutoJudge.setText(_translate("Form", "自动检测"))
        self.label_4.setText(_translate("Form", "周期2"))
        self.label_6.setText(_translate("Form", "周期3"))
        self.label_3.setText(_translate("Form", "峰-峰值2"))
        self.pp_value_max.setText(_translate("Form", "最大峰峰值："))
        self.pp_value_min.setText(_translate("Form", "最小峰峰值："))
        self.period.setText(_translate("Form", "平均周期："))
        self.label_9.setText(_translate("Form", "（变更数据后请重新勾选自动检测）"))
        self.label_10.setText(_translate("Form", "选择串口"))
        self.label_11.setText(_translate("Form", "波特率"))
        self.SerOpenBtn.setText(_translate("Form", "打开串口"))
        self.groupBox_2.setTitle(_translate("Form", "自动标定"))
        self.label_13.setText(_translate("Form", "转子个数"))
        self.label_12.setText(_translate("Form", "测量次数"))
        self.CalibrationBtn.setText(_translate("Form", "自动标定"))

